name: Publish Docker image

on: push

jobs:
  build:
    env:
      uno: 'soyUNO'
      dos: 'soyDOS'
      tres: 'soyTRES'
      state_repo: 'gustavoborragan/repo_b'

      state_repo_git_user: 'github-actions'
      state_repo_git_mail: 'github-actions@github.com'

    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: contrucción imagen
        id: image
        run: |
                echo "::set-output name=image_name:::pericoDeLosPalotes"
        
      - name: Envío evento
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.ACCESS_TOKEN }}" \
            --request POST \
            --data '{
              "event_type": "proba", 
              "client_payload": {
                "image": "${{ steps.image.outputs.image_name }}",
                "uno": "${{ env.uno }}",
                "dos": "${{ env.dos }}",
                "tres": "${{ env.tres }}" }}'\
            https://api.github.com/repos/${{ env.state_repo }}/dispatches

