name: Publish Docker image

on: push

env:
  nombre_cluster: k8s
  region: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }} us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get pods
        run: |
                mkdir -p ~/.kube
                aws eks update-kubeconfig --name ${{ env.nombre_cluster }}
                cat ~/.kube/config

