name: Publish Docker image

on: push

jobs:
  build:
    env:
      uno: 'soyUNO'
      dos: 'soyDOS'
      tres: 'soyTRES'
      state_repo: 'gustavoborragan/repo_b'

      state_repo_git_user: 'github-actions'
      state_repo_git_mail: 'github-actions@github.com'

    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get pods
        run: |
                mkdir -p ~/.kube
                update-kubeconfig
                cat ~/.kube/config

